name: Sync Fork

on:
  schedule:
    - cron: '0 7 * * *'  # 每天 UTC 时间 7 点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: gblw1218/ios_rule_script
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add Upstream
      run: git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git

    - name: Fetch Upstream
      run: git fetch upstream

    - name: Check for Changes
      id: check_changes
      run: |
        UPSTREAM=${{ github.event.repository.default_branch }}
        if git diff --quiet HEAD..upstream/$UPSTREAM; then
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

    - name: Merge Upstream
      if: steps.check_changes.outputs.changes == 'true'
      run: git merge upstream/master

    - name: Push Changes
      if: steps.check_changes.outputs.changes == 'true'
      run: git push origin master

    - name: Notify No Changes
      if: steps.check_changes.outputs.changes == 'false'
      run: echo "上游无变动，无须同步."

    - name: Notify Sync Complete
      if: steps.check_changes.outputs.changes == 'true'
      run: echo "同步成功完成."