name: Sync Fork

on:
  schedule:
    - cron: '0 7 * * *'  # 每天 UTC 时间 7 点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Set Env
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: gblw1218/ios_rule_script
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add Upstream
      run: git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git

    - name: Fetch Upstream
      run: git fetch upstream

    - name: Merge Upstream
      run: git merge upstream/master --allow-unrelated-histories

    - name: Push Changes
      run: git push origin master